#!/usr/bin/env php
<?php 

require __DIR__.'/autoload.php';

use \Symfony\Component\Console\Application;
use \SonSlim\Modules\Core\src\Commands\ServerCommand;

$application = new Application;

$application->add(new ServerCommand());
$application->run();



